#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <regex>
#include <map>
#include <algorithm>
#include <filesystem>
#include <cstdlib>

namespace fs = std::filesystem;

struct OpcodeInfo
{
    std::string name;
    std::uint8_t value;
    std::string group;
    std::string handler;
    std::string file;
};

struct Instruction
{
    std::uint8_t opcode;
    std::int64_t operand;
};

std::vector<OpcodeInfo> parse_opcodes(const fs::path& opcodes_dir)
{
    std::vector<OpcodeInfo> opcodes;

    // Regex to match: /* [[Opcode::NAME, 0xVALUE, Group::GROUP]] */ ... void HANDLER(

    std::regex pattern(
        R"(/\*\s*\[\[Opcode::(\w+),\s*0x([0-9A-Fa-f]+),\s*Group::(\w+)\]\]\s*\*/\s*(?:static\s+)?void\s+(h_\w+))"
    );

    for (const auto& entry : fs::recursive_directory_iterator(opcodes_dir))
    {
        if (entry.path().extension() != ".h")
            continue;

        std::ifstream file(entry.path());
        if (!file)
            continue;

        std::string content((std::istreambuf_iterator<char>(file)),
                           std::istreambuf_iterator<char>());

        std::smatch match;
        std::string::const_iterator search_start(content.cbegin());

        while (std::regex_search(search_start, content.cend(), match, pattern))
        {
            OpcodeInfo info;
            info.name = match[1].str();
            info.value = static_cast<std::uint8_t>(std::stoul(match[2].str(), nullptr, 16));
            info.group = match[3].matched ? match[3].str() : "MISC";
            info.handler = match[4].str();
            info.file = entry.path().filename().string();

            opcodes.push_back(info);
            search_start = match.suffix().first;
        }
    }


    std::sort(opcodes.begin(), opcodes.end(),
              [](const OpcodeInfo& a, const OpcodeInfo& b) { return a.value < b.value; });

    return opcodes;
}

void generate_opcode_enum(const std::vector<OpcodeInfo>& opcodes, const fs::path& output_dir)
{
    std::ofstream out(output_dir / "opcode_enum.inl");

    out << "// Auto-generated by opcode_generator - DO NOT EDIT\n\n";
    out << "enum class opcode : std::uint8_t\n{\n";

    for (const auto& op : opcodes)
    {
        out << "    " << op.name << " = 0x" << std::hex << std::uppercase
            << static_cast<int>(op.value) << ",\n";
    }


    if (!opcodes.empty())
    {
        auto max_val = std::max_element(opcodes.begin(), opcodes.end(),
                                       [](const auto& a, const auto& b) { return a.value < b.value; });
        out << "\n    COUNT = 0x" << std::hex << std::uppercase
            << (static_cast<int>(max_val->value) + 1) << ",\n";
    }

    out << "};\n";
}

void generate_handlers_table(const std::vector<OpcodeInfo>& opcodes, const fs::path& output_dir)
{
    std::ofstream out(output_dir / "handlers_table.inl");

    out << "// Auto-generated by opcode_generator - DO NOT EDIT\n\n";
    out << "static constexpr std::array<handler_t, opcode_count> handlers_ =\n{\n";


    std::uint8_t max_value = 0;
    if (!opcodes.empty())
    {
        auto max_op = std::max_element(opcodes.begin(), opcodes.end(),
                                      [](const auto& a, const auto& b) { return a.value < b.value; });
        max_value = max_op->value;
    }

    std::uint8_t current_idx = 0;

    for (const auto& op : opcodes)
    {

        while (current_idx < op.value)
        {
            out << "    &assembly::h_nop,      // 0x" << std::hex << std::uppercase
                << static_cast<int>(current_idx) << " (unmigrated)\n";
            current_idx++;
        }


        std::string enable_macro = "ENABLE_" + op.group;

        out << "#if " << enable_macro << "\n";
        out << "    &assembly::" << op.handler << ",";
        out << "     // 0x" << std::hex << std::uppercase << static_cast<int>(op.value);
        out << " " << op.name << "\n";
        out << "#else\n";
        out << "    &assembly::h_nop,      // 0x" << std::hex << std::uppercase
            << static_cast<int>(op.value) << " " << op.name << " (disabled)\n";
        out << "#endif\n";

        current_idx++;
    }



    const std::uint8_t expected_count = 0x1B;  // Update this when adding more opcodes
    while (current_idx < expected_count)
    {
        out << "    &assembly::h_nop,      // 0x" << std::hex << std::uppercase
            << static_cast<int>(current_idx) << " (unmigrated - old handler still in assembly.h)\n";
        current_idx++;
    }

    out << "};\n";
}

void generate_disassembler(const std::vector<OpcodeInfo>& opcodes, const fs::path& output_dir)
{

    {
        std::ofstream out(output_dir / "disassembler.h");
        out << "// Auto-generated by opcode_generator - DO NOT EDIT\n\n";
        out << "#ifndef VARABLIZER_DISASSEMBLER_H\n";
        out << "#define VARABLIZER_DISASSEMBLER_H\n\n";
        out << "#include \"../opcodes.h\"\n";
        out << "#include <string_view>\n\n";
        out << "namespace execute\n{\n\n";
        out << "[[nodiscard]] std::string_view opcode_to_string(opcode op) noexcept;\n\n";
        out << "} // namespace execute\n\n";
        out << "#endif // VARABLIZER_DISASSEMBLER_H\n";
    }


    {
        std::ofstream out(output_dir / "disassembler.cpp");
        out << "// Auto-generated by opcode_generator - DO NOT EDIT\n\n";
        out << "#include \"disassembler.h\"\n\n";
        out << "namespace execute\n{\n\n";
        out << "std::string_view opcode_to_string(opcode op) noexcept\n{\n";
        out << "    switch (op)\n    {\n";

        for (const auto& op : opcodes)
        {
            out << "    case opcode::" << op.name << ":\n";
            out << "        return \"" << op.name << "\";\n";
        }

        out << "    default:\n";
        out << "        return \"UNKNOWN\";\n";
        out << "    }\n}\n\n";
        out << "} // namespace execute\n";
    }
}

void generate_documentation(const std::vector<OpcodeInfo>& opcodes, const fs::path& output_dir)
{
    std::ofstream out(output_dir / "OPCODES.md");

    out << "# Opcodes Reference\n\n";
    out << "*Auto-generated by opcode_generator - DO NOT EDIT*\n\n";


    std::map<std::string, std::vector<const OpcodeInfo*>> by_group;
    for (const auto& op : opcodes)
        by_group[op.group].push_back(&op);

    out << "## Summary\n\n";
    out << "| Opcode | Value | Group | Handler |\n";
    out << "|--------|-------|-------|----------|\n";

    for (const auto& op : opcodes)
    {
        out << "| " << op.name << " | 0x" << std::hex << std::uppercase
            << static_cast<int>(op.value) << " | " << op.group
            << " | `" << op.handler << "` |\n";
    }

    out << "\n## By Group\n\n";

    for (const auto& [group, ops] : by_group)
    {
        out << "### " << group << "\n\n";
        for (const auto* op : ops)
        {
            out << "- **" << op->name << "** (0x" << std::hex << std::uppercase
                << static_cast<int>(op->value) << ") - `" << op->handler << "`\n";
        }
        out << "\n";
    }

    out << "\n---\n";
    out << "*Total opcodes: " << std::dec << opcodes.size() << "*\n";
}

int main(int argc, char** argv)
{
    if (argc != 3)
    {
        std::cerr << "Usage: " << argv[0] << " <opcodes_dir> <output_dir>\n";
        return 1;
    }

    fs::path opcodes_dir = argv[1];
    fs::path output_dir = argv[2];

    if (!fs::exists(opcodes_dir) || !fs::is_directory(opcodes_dir))
    {
        std::cerr << "Error: opcodes directory does not exist: " << opcodes_dir << "\n";
        return 1;
    }

    fs::create_directories(output_dir);

    std::cout << "Scanning opcodes in: " << opcodes_dir << "\n";
    auto opcodes = parse_opcodes(opcodes_dir);
    std::cout << "Found " << opcodes.size() << " opcodes\n";

    std::cout << "*Generating opcode_enum.inl...\n";
    generate_opcode_enum(opcodes, output_dir);

    std::cout << "Generating handlers_table.inl...\n";
    generate_handlers_table(opcodes, output_dir);

    std::cout << "Generating disassembler...\n";
    generate_disassembler(opcodes, output_dir);

    std::cout << "Generating OPCODES.md...\n";
    generate_documentation(opcodes, output_dir);

    std::cout << "Code generation complete!\n";

    return 0;
}
